// GENERATED BY scripts/generate_ts_client.py — DO NOT EDIT.

/** Every mounted operation, by id. A union rather than ``string``, so a typo is a type error. */
export type OpId =
  | "AccessService.audit"
  | "AccessService.create_principal"
  | "AccessService.delete_principal"
  | "AccessService.grant"
  | "AccessService.list_grants"
  | "AccessService.list_principals"
  | "AccessService.list_tokens"
  | "AccessService.mint_token"
  | "AccessService.revoke_grant"
  | "AccessService.revoke_token"
  | "ConversationService.ingest_conversation"
  | "DocumentService.chunk_document"
  | "DocumentService.create_document"
  | "DocumentService.create_link"
  | "DocumentService.delete_document"
  | "DocumentService.delete_link"
  | "DocumentService.embed_document"
  | "DocumentService.extract_facts_endpoint"
  | "DocumentService.get_ancestors"
  | "DocumentService.get_children"
  | "DocumentService.get_document"
  | "DocumentService.get_document_blob"
  | "DocumentService.get_document_cells"
  | "DocumentService.get_document_evidence"
  | "DocumentService.get_document_image"
  | "DocumentService.get_document_region"
  | "DocumentService.get_document_tokens"
  | "DocumentService.get_links"
  | "DocumentService.get_root_documents"
  | "DocumentService.get_siblings"
  | "DocumentService.get_subtree"
  | "DocumentService.list_documents"
  | "DocumentService.raptor_portfolio_summarize"
  | "DocumentService.raptor_summarize_document"
  | "DocumentService.segment_document"
  | "DocumentService.split_document"
  | "DocumentService.update_document"
  | "GraphService.get_centrality"
  | "GraphService.get_communities"
  | "GraphService.get_diff"
  | "GraphService.get_neighbors"
  | "GraphService.get_spines"
  | "GraphService.get_stats"
  | "GraphService.get_subtree_authority"
  | "GraphService.post_lint"
  | "IndexService.add_root_to_index"
  | "IndexService.create_index"
  | "IndexService.delete_index"
  | "IndexService.get_index"
  | "IndexService.get_index_roots"
  | "IndexService.index_single_document"
  | "IndexService.list_indexes"
  | "IndexService.refresh_index"
  | "IndexService.remove_root_from_index"
  | "IngestService.analyze_ingest"
  | "IngestService.explain_ingest"
  | "IngestService.file_frontier"
  | "IngestService.ingest_content"
  | "IngestService.list_registered_pipelines"
  | "IngestService.upload_file"
  | "MetaService.capabilities"
  | "OntologyService.create_binding"
  | "OntologyService.delete_binding"
  | "OntologyService.delete_ontology"
  | "OntologyService.derive_binding"
  | "OntologyService.get_ontology"
  | "OntologyService.import_ontology"
  | "OntologyService.list_bindings"
  | "OntologyService.list_ontologies"
  | "OntologyService.validate_binding"
  | "RdfService.export_turtle"
  | "SearchContextService.create_context"
  | "SearchContextService.delete_context"
  | "SearchContextService.get_context"
  | "SearchContextService.list_contexts"
  | "SearchContextService.update_context"
  | "SearchService.auto_search"
  | "SearchService.bm25_search"
  | "SearchService.fulltext_search"
  | "SearchService.hybrid_search"
  | "SearchService.maxsim_search"
  | "SearchService.quick_search"
  | "SearchService.synthesize_search"
  | "SearchService.vector_search"
  | "TemplateService.create_template"
  | "TemplateService.get_template"
  | "TemplateService.list_templates"
  | "TemplateService.render_template"
  | "TemplateService.search_templates"
  | "TemplateService.update_template"
  | "TripleService.create_predicate"
  | "TripleService.create_triple"
  | "TripleService.delete_predicate"
  | "TripleService.delete_triple"
  | "TripleService.find_path"
  | "TripleService.get_predicate"
  | "TripleService.get_triple"
  | "TripleService.invalidate_triple"
  | "TripleService.list_predicates"
  | "TripleService.query_triples"
  | "TripleService.supersede_triple"
  | "TripleService.upsert_triple"
  | "UsetypePresentationService.create_presentation"
  | "UsetypePresentationService.delete_presentation"
  | "UsetypePresentationService.get_presentation"
  | "UsetypePresentationService.list_presentations"
  | "UsetypePresentationService.update_presentation"
  | "ViewService.expand_children"
  | "ViewService.get_back_references"
  | "ViewService.get_breadcrumbs"
  | "ViewService.view_document"
  | "get_config"
  | "health_check"
  | "health_check_liveness"
  | "health_check_llm"
  | "runner_embed"
  | "runner_embed_tokens"
  | "runner_info";

/** One operation, as ``operations.js`` carries it. */
export interface Operation {
  /** ``ServiceClass.method`` for an ``@expose``'d operation, the route name otherwise. */
  op_id: OpId;
  /** The document's own ``operationId``, mangled by FastAPI out of the name, path and method. */
  operation_id: string;
  /** The ``RemoteJmftsClient`` method name, or ``null`` where the route is hand-written. */
  python_verb: string | null;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  /** The path template, with ``{name}`` placeholders. */
  path: string;
  path_params: ReadonlyArray<string>;
  /** Path parameters whose values keep their slashes (Starlette's ``:path`` converter). */
  path_slash_params: ReadonlyArray<string>;
  query_params: ReadonlyArray<string>;
  /** The single JSON or raw body argument, or ``null`` for none and for multipart. */
  body_param: string | null;
  body_media_type: string | null;
  /** Multipart fields that travel beside a file part, sent as JSON text. */
  form_params: ReadonlyArray<string>;
  file_params: ReadonlyArray<string>;
  /** ``true`` when the response is bytes: the call resolves to a ``Blob``, not parsed JSON. */
  binary: boolean;
  response_media_type: string | null;
  success_status: number;
  /** The security scheme the corrected document says this operation takes, or ``null``. */
  security_scheme: string | null;
  tags: ReadonlyArray<string>;
  summary: string;
}

export declare const OPERATIONS: Readonly<Record<OpId, Operation>>;
export declare const OP_IDS: ReadonlyArray<OpId>;
