"""The browser client must match the surface it was generated from.

``docs/SPRINT_0_6_0.md`` Block F step 23, IC-6. The same seal ``tests/test_client_codegen.py``
puts on ``_verbs.py`` and ``tests/test_reference_docs.py`` puts on ``docs/reference/``, for
the same reason: a generated artefact checked into the tree is worth exactly what its
staleness check is worth, and a front end generated against a route table that has since
moved renders controls for operations that are not there.

These need no database and no browser. They read the tree, build the app's OpenAPI document
in memory, and — where a JavaScript runtime is available — execute the generated module
against a stubbed ``fetch`` to check that a call really does emit one event and that a binary
operation really does hand back bytes.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import textwrap
from pathlib import Path

import pytest

from jmfts_core.registry import REGISTRY
from jmfts_core.rest.main import app
from jmfts_core.rest.wiring import iter_mounted_api_routes
from scripts.generate_ts_client import (
    GENERATED_FILES,
    ROUTE_EXTENSION,
    TARGET_DIR,
    GenerationError,
    document,
    generate,
)

REPO = Path(__file__).resolve().parents[1]
STATIC = REPO / "jmfts-web" / "jmfts_web" / "static"

#: The hand-written half of the client. ``GENERATED_FILES`` is the other half, and
#: ``test_the_client_directory_holds_nothing_else`` refuses anything in neither set — the
#: directory ships wholesale inside the wheel, so a file dropped in here would reach users
#: without ever passing a check.
RUNTIME_FILES = frozenset(
    {
        "transport.js",
        "transport.d.ts",
        "copyout.js",
        "copyout.d.ts",
        "index.js",
        "index.d.ts",
    }
)

#: The nine fields of a call event, verbatim from IC-6 in the sprint plan's Part 5.1 table.
#: Written out here rather than imported, because a contract that is pinned by reading the
#: implementation is pinned to whatever the implementation happens to say.
IC6_CALL_EVENT = (
    "op_id",
    "method",
    "path",
    "path_params",
    "query",
    "body",
    "status",
    "response",
    "ms",
)

#: The mounted routes that are hand-written FastAPI endpoints rather than ``@expose``'d
#: service methods, and which therefore have no ``_verbs.py`` counterpart. Named rather than
#: counted so that moving one into the registry is a decision somebody writes down.
ROUTES_WITHOUT_A_PYTHON_VERB = frozenset(
    {
        "get_config",
        "health_check",
        "health_check_liveness",
        "health_check_llm",
        "runner_embed",
        "runner_embed_tokens",
        "runner_info",
    }
)


def operation_table(text: str | None = None) -> dict:
    """The generated operation table, read back as data.

    ``operations.js`` writes its table as strict JSON framed on lines of its own, precisely
    so that this can compare it against the live registry.
    """
    text = text if text is not None else (TARGET_DIR / "operations.js").read_text(encoding="utf-8")
    opener = "export const OPERATIONS = Object.freeze(\n"
    start = text.index(opener) + len(opener)
    end = text.index("\n);\n", start)
    return json.loads(text[start:end])


# --------------------------------------------------------------------- the staleness seal


def test_the_generated_browser_client_is_current():
    """``python -m scripts.generate_ts_client`` produces exactly the checked-in files."""
    for name, expected in generate().items():
        path = TARGET_DIR / name
        assert path.exists(), f"{path} is missing; run python -m scripts.generate_ts_client"
        assert path.read_text(encoding="utf-8") == expected, (
            f"{path} is stale. The exposed surface changed and the front end was not "
            "regenerated. Run: python -m scripts.generate_ts_client"
        )


def test_the_client_directory_holds_nothing_else():
    """Every file in the bundle's client directory is generated or is the named runtime."""
    on_disk = {p.name for p in TARGET_DIR.iterdir() if p.is_file()}
    accounted = set(GENERATED_FILES) | RUNTIME_FILES
    assert on_disk == accounted, (
        f"unaccounted: {sorted(on_disk - accounted)}; missing: {sorted(accounted - on_disk)}. "
        "Add the file to scripts/generate_ts_client.GENERATED_FILES, or to RUNTIME_FILES "
        "here, or take it out of a directory the wheel ships wholesale."
    )


def test_every_generated_file_carries_the_do_not_edit_banner():
    """A reader who opens one of these has to be told not to edit it."""
    for name in GENERATED_FILES:
        head = (TARGET_DIR / name).read_text(encoding="utf-8").splitlines()[0]
        assert "GENERATED BY scripts/generate_ts_client.py" in head, f"{name}: {head!r}"


# --------------------------------------------------------------------- against the surface


def test_the_operation_table_covers_the_whole_mounted_surface():
    """One entry per mounted route — the front end cannot be a subset of the appliance.

    This is the check that makes the generator worth having. ``_verbs.py`` covers the 108
    ``@expose``'d operations; the document covers all 115, because seven routes are written
    by hand in ``rest/main.py`` and the browser needs them (``/health`` most of all: it is
    how the page tells "no credential" from "nothing is running").
    """
    table = operation_table()
    mounted = {route.name for route in iter_mounted_api_routes(app)}
    assert (
        set(table) == mounted
    ), f"missing: {sorted(mounted - set(table))}, extra: {sorted(set(table) - mounted)}"


def test_every_exposed_operation_names_its_python_verb():
    """An operation id maps to a ``_verbs.py`` method name — property 3 of step 23.

    That mapping is what copy-out rests on: the event prints as a ``RemoteJmftsClient`` call
    because the table says which method it is. A wrong name here is a worked example that
    does not run.
    """
    table = operation_table()
    expected = {spec.name: spec.func.__name__ for spec in REGISTRY}
    actual = {op_id: row["python_verb"] for op_id, row in table.items() if row["python_verb"]}
    assert actual == expected


def test_the_routes_without_a_python_verb_are_the_seven_hand_written_ones():
    """A route that gained an ``@expose`` must leave this list, and one that lost it join."""
    table = operation_table()
    without = {op_id for op_id, row in table.items() if not row["python_verb"]}
    assert without == ROUTES_WITHOUT_A_PYTHON_VERB, (
        f"gained: {sorted(without - ROUTES_WITHOUT_A_PYTHON_VERB)}, "
        f"lost: {sorted(ROUTES_WITHOUT_A_PYTHON_VERB - without)}"
    )


def test_client_method_names_are_unique():
    """The client is one flat namespace, exactly as ``_verbs.py`` is."""
    members = [op_id.split(".")[-1] for op_id in operation_table()]
    duplicates = sorted({name for name in members if members.count(name) > 1})
    assert not duplicates, f"two operations want one client method name: {duplicates}"


def test_every_operation_has_a_client_method():
    source = (TARGET_DIR / "verbs.js").read_text(encoding="utf-8")
    for op_id in operation_table():
        member = op_id.split(".")[-1]
        assert f"  {member}(args = {{}}) {{" in source, f"verbs.js has no method for {op_id}"


def test_the_starlette_path_converter_survives_into_the_client():
    """The fact the OpenAPI document cannot carry, and the reason for the route stamp.

    ``compile_path`` strips ``{usetype:path}`` down to ``{usetype}``, so a client generated
    from the document alone would percent-encode a slash in that value and send a request the
    server does not match. ``path_slash_params`` is how the table says otherwise.
    """
    table = operation_table()
    expected = {
        route.name: sorted(re.findall(r"\{([A-Za-z0-9_]+):path\}", route.path))
        for route in iter_mounted_api_routes(app)
        if ":path}" in route.path
    }
    assert expected, "no route uses a converter any more; this test has nothing to hold"
    for op_id, names in expected.items():
        assert sorted(table[op_id]["path_slash_params"]) == names
    plain = [
        op_id for op_id, row in table.items() if row["path_slash_params"] and op_id not in expected
    ]
    assert not plain, f"{plain} claim a converter no route declares"


def test_the_document_this_generator_reads_is_stamped_with_the_route_table_facts():
    """Every operation carries ``x-jmfts-route``, and it names a route that exists."""
    doc = document()
    mounted = {route.name for route in iter_mounted_api_routes(app)}
    for path, item in doc["paths"].items():
        for method, operation in item.items():
            if method in ("get", "post", "put", "patch", "delete"):
                stamp = operation.get(ROUTE_EXTENSION)
                assert stamp, f"{method.upper()} {path} is unstamped"
                assert stamp["name"] in mounted


def test_the_security_correction_reaches_the_client():
    """``/health`` takes no credential and ``/runner`` takes the other one.

    ``rest/main.py`` rewrites the generated ``security`` block to match the gate that
    actually runs, and reading the document rather than the route table is what lets the
    front end inherit that. A client that sent the API token to ``/runner`` would be told 401
    with nothing on the page to explain it.
    """
    table = operation_table()
    assert table["health_check_liveness"]["security_scheme"] is None
    assert table["runner_embed"]["security_scheme"] == "JMFTSRunnerKey"
    assert table["SearchService.hybrid_search"]["security_scheme"] == "JMFTSToken"


# ------------------------------------------------------------------- the binary path (IC-2)


def _synthetic(**overrides) -> dict:
    """A minimal document with one JSON operation and one binary one.

    ``wt/bytes`` is adding ``/documents/{id}/blob``, ``/image`` and ``/region`` in parallel
    and they are not in this tree yet, so the branch that returns bytes instead of parsing
    JSON is covered here rather than against a route that does not exist. The binary response
    is the literal shape ``rest/wiring.py::_BINARY_SCHEMA`` writes.
    """
    image = {
        "tags": ["documents"],
        "summary": "One rendered page",
        "operationId": "DocumentService_page_image_documents__document_id__image_get",
        "security": [{"JMFTSToken": []}],
        "parameters": [
            {
                "name": "document_id",
                "in": "path",
                "required": True,
                "schema": {"type": "integer"},
            },
            {"name": "page", "in": "query", "required": False, "schema": {"type": "integer"}},
        ],
        "responses": {
            "200": {
                "description": "Successful Response",
                "content": {"image/png": {"schema": {"type": "string", "format": "binary"}}},
            }
        },
        ROUTE_EXTENSION: {
            "name": "DocumentService.page_image",
            "path_template": "/documents/{document_id}/image",
            "body_param": None,
            "python_verb": "page_image",
        },
    }
    image.update(overrides)
    return {
        "openapi": "3.1.0",
        "paths": {
            "/documents/{document_id}/image": {"get": image},
            "/search": {
                "post": {
                    "tags": ["search"],
                    "summary": "Search",
                    "operationId": "SearchService_search_search_post",
                    "security": [{"JMFTSToken": []}],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/SearchRequest"}
                            }
                        },
                    },
                    "responses": {
                        "200": {
                            "description": "OK",
                            "content": {"application/json": {"schema": {"type": "object"}}},
                        }
                    },
                    ROUTE_EXTENSION: {
                        "name": "SearchService.search",
                        "path_template": "/search",
                        "body_param": "request",
                        "python_verb": "search",
                    },
                }
            },
        },
        "components": {
            "securitySchemes": {"JMFTSToken": {"type": "http", "scheme": "bearer"}},
            "schemas": {
                "SearchRequest": {
                    "type": "object",
                    "properties": {"query": {"type": "string"}},
                    "required": ["query"],
                }
            },
        },
    }


def test_a_binary_response_is_read_as_bytes_and_a_json_one_is_not():
    table = operation_table(generate(_synthetic())["operations.js"])
    image = table["DocumentService.page_image"]
    assert image["binary"] is True
    assert image["response_media_type"] == "image/png"
    assert table["SearchService.search"]["binary"] is False


def test_a_binary_operation_is_typed_as_a_blob_not_as_a_parsed_shape():
    types = generate(_synthetic())["verbs.d.ts"]
    start = types.index("  page_image(args:")
    signature = types[start : types.index("\n\n", start)]
    assert "document_id: number;" in signature
    assert "page?: number;" in signature
    assert signature.rstrip().endswith("Promise<Blob>;"), signature


def test_a_non_json_response_that_does_not_declare_bytes_is_refused():
    """The failure mode ``_BINARY_SCHEMA`` exists to prevent, asserted rather than assumed.

    A route answering ``image/png`` with no schema would be documented as an empty body, and
    a generator that shrugged at that would render a JSON-parsing call for a PNG.
    """
    doc = _synthetic()
    operation = doc["paths"]["/documents/{document_id}/image"]["get"]
    operation["responses"]["200"]["content"]["image/png"] = {}
    with pytest.raises(GenerationError, match="must declare"):
        generate(doc)


def test_an_unstamped_operation_is_refused_rather_than_guessed_at():
    doc = _synthetic()
    del doc["paths"]["/search"]["post"][ROUTE_EXTENSION]
    with pytest.raises(GenerationError, match="carries no usable"):
        generate(doc)


def test_a_json_body_with_no_named_parameter_is_refused():
    """The document cannot name a body, so the stamp must — and copy-out needs the name."""
    doc = _synthetic()
    doc["paths"]["/search"]["post"][ROUTE_EXTENSION]["body_param"] = None
    with pytest.raises(GenerationError, match="names no parameter"):
        generate(doc)


def test_a_credential_this_client_cannot_send_is_refused():
    doc = _synthetic()
    doc["components"]["securitySchemes"]["JMFTSToken"] = {"type": "apiKey", "in": "cookie"}
    with pytest.raises(GenerationError, match="bearer credentials"):
        generate(doc)


# ----------------------------------------------------------------------- the call event


def test_the_call_event_is_exactly_the_nine_fields_of_ic6():
    """IC-6 fixes the shape, and the runtime names it in one place.

    Pinned by reading ``CALL_EVENT_FIELDS`` out of the source rather than by executing it, so
    this holds in an environment with no JavaScript runtime. The node test below then checks
    that an event actually produced has those keys and no others.
    """
    source = (TARGET_DIR / "transport.js").read_text(encoding="utf-8")
    start = source.index("export const CALL_EVENT_FIELDS = Object.freeze([")
    body = source[start : source.index("]);", start)]
    declared = tuple(name.strip().strip('",') for name in body.splitlines()[1:] if name.strip())
    assert declared == IC6_CALL_EVENT


def test_nothing_in_the_bundle_loads_from_the_network():
    """The appliance is expected to run air-gapped.

    A page that renders blank without internet is worse than no page, so there is no CDN, no
    font host and no analytics beacon anywhere in the bundle. Checked over the whole static
    directory rather than the client alone, because the failure arrives by somebody pasting
    a ``<script src>`` into the HTML.
    """
    # A URL in prose or in a comment is documentation, and ``copyout.js`` prints one as the
    # default origin of a Python example. What must not exist is a URL the browser FETCHES:
    # a script or stylesheet source, a module import, or a CSS url().
    fetching = re.compile(
        r"""(?:src|href)\s*=\s*["']https?:|from\s+["']https?:|import\(["']https?:|url\(\s*["']?https?:""",
        re.IGNORECASE,
    )
    offenders = []
    for path in sorted(STATIC.rglob("*")):
        if not path.is_file() or path.suffix not in (".html", ".js", ".css"):
            continue
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if fetching.search(line):
                offenders.append(f"{path.relative_to(STATIC)}:{number}: {line.strip()}")
    assert not offenders, "the bundle reaches outside this origin: " + str(offenders)


def test_copy_out_cannot_print_a_credential():
    """The third property of step 23 says the token is elided, and this is what holds it.

    ``copyout.js`` names the environment variable each credential lives in and never reads
    one. Asserted structurally: the module must not touch storage or the transport's
    credential reader, because a renderer that could get the value could print it.
    """
    source = (TARGET_DIR / "copyout.js").read_text(encoding="utf-8")
    for forbidden in ("sessionStorage", "localStorage", "getCredential", "credentialFromSession"):
        assert forbidden not in source, f"copyout.js reaches for {forbidden}"


def test_the_page_keeps_the_token_in_session_storage_and_out_of_the_url():
    """Step 19's rule, which step 23 had to preserve while replacing the fetch wrapper."""
    # ``localStorage`` is NAMED in both files, in the comments that say why it is not used.
    # What must not exist is a call against it: a credential that outlives the tab.
    used = re.compile(r"(?<![.\w])(?:window\.)?localStorage\s*\.")
    page = (STATIC / "index.html").read_text(encoding="utf-8")
    assert "sessionStorage" in page
    assert not used.search(page), "the page writes to localStorage"
    transport = (TARGET_DIR / "transport.js").read_text(encoding="utf-8")
    assert 'JMFTSToken: "jmfts.token"' in transport
    assert not used.search(transport), "the transport writes to localStorage"


# ------------------------------------------------------------------- run it, if we can


NODE = shutil.which("node")
needs_node = pytest.mark.skipif(NODE is None, reason="no JavaScript runtime on PATH")

HARNESS = textwrap.dedent("""
    import assert from "node:assert/strict";
    import { JmftsClient, asCurl, asFetch, asPython } from "./index.js";

    const IC6 = %(fields)s;
    const seen = [];
    const replies = [];

    const client = new JmftsClient({
      baseUrl: "http://appliance:8100",
      getCredential: () => "SECRET-TOKEN",
      fetchImpl: async () => replies.shift(),
      now: (() => { let t = 0; return () => (t += 12); })(),
    });
    client.onCall((event) => seen.push(event));

    // --- a JSON operation ----------------------------------------------------------
    replies.push(new Response(JSON.stringify({ hits: 3 }), {
      status: 200, headers: { "content-type": "application/json" },
    }));
    const result = await client.search({ request: { query: "kittens" } });
    assert.deepEqual(result, { hits: 3 });
    assert.equal(seen.length, 1, "one call, one event");
    assert.deepEqual(Object.keys(seen[0]), IC6, "the event is exactly IC-6's nine fields");
    assert.equal(seen[0].op_id, "SearchService.search");
    assert.equal(seen[0].path, "/search");
    assert.deepEqual(seen[0].body, { query: "kittens" });
    assert.equal(seen[0].status, 200);
    assert.equal(seen[0].ms, 12);

    // --- a binary operation returns bytes, not parsed JSON --------------------------
    replies.push(new Response(new Uint8Array([137, 80, 78, 71]), {
      status: 200, headers: { "content-type": "image/png" },
    }));
    const image = await client.page_image({ document_id: 42, page: 3 });
    assert.ok(image instanceof Blob, "a binary operation resolves to bytes");
    assert.equal(new Uint8Array(await image.arrayBuffer())[0], 137);
    assert.equal(seen[1].path, "/documents/42/image");
    assert.deepEqual(seen[1].query, { page: 3 });

    // --- replay: an event is a call plus its arguments ------------------------------
    replies.push(new Response(JSON.stringify({ hits: 9 }), {
      status: 200, headers: { "content-type": "application/json" },
    }));
    const again = await client.replay(seen[0], { request: { query: "puppies" } });
    assert.deepEqual(again, { hits: 9 });
    assert.deepEqual(seen[2].body, { query: "puppies" });

    // --- copy-out, and the credential is in none of it -------------------------------
    const printed = [
      asCurl(seen[0], { baseUrl: "http://appliance:8100" }),
      asPython(seen[0], { baseUrl: "http://appliance:8100" }),
      asFetch(seen[0], { baseUrl: "http://appliance:8100" }),
    ];
    for (const text of printed) {
      assert.ok(!text.includes("SECRET-TOKEN"), "the credential must never be printed");
    }
    assert.ok(printed[0].includes('Bearer $JMFTS_API_TOKEN'), printed[0]);
    assert.ok(printed[0].includes("curl -sS -X POST"), printed[0]);
    assert.ok(printed[1].includes("client.search("), printed[1]);
    assert.ok(printed[1].includes('"query": "kittens"'), printed[1]);
    assert.ok(printed[2].includes("await fetch("), printed[2]);
    assert.ok(asCurl(seen[1]).includes("-o out.png"), "a binary call saves its bytes");

    // --- an argument the operation does not declare is refused ----------------------
    await assert.rejects(
      client.search({ request: { query: "x" }, limitt: 5 }),
      /no parameter "limitt"/,
    );

    // --- a 4xx throws, and the event still records it -------------------------------
    replies.push(new Response(JSON.stringify({ detail: "nope" }), {
      status: 404, headers: { "content-type": "application/json" },
    }));
    await assert.rejects(client.search({ request: { query: "x" } }), /HTTP 404: nope/);
    assert.equal(seen.at(-1).status, 404);
    assert.deepEqual(seen.at(-1).response, { detail: "nope" });

    console.log("ok");
    """)


@needs_node
def test_the_generated_client_really_emits_one_event_per_call(tmp_path):
    """Execute the thing, against a synthetic surface that carries a binary operation.

    Everything above reads text. This runs it: one call, one event, nine fields; a binary
    operation hands back bytes; an event replays with an edited argument; and none of the
    three copy-out renderings contains the credential the client was given.
    """
    for name, text in generate(_synthetic()).items():
        (tmp_path / name).write_text(text, encoding="utf-8")
    for name in RUNTIME_FILES:
        shutil.copyfile(TARGET_DIR / name, tmp_path / name)
    harness = tmp_path / "harness.mjs"
    harness.write_text(HARNESS % {"fields": json.dumps(list(IC6_CALL_EVENT))}, encoding="utf-8")

    done = subprocess.run([NODE, str(harness)], capture_output=True, text=True, cwd=tmp_path)
    assert done.returncode == 0, done.stderr or done.stdout
    assert done.stdout.strip().endswith("ok")


#: Two real calls, printed as Python, so the next test can bind them against the real client.
#: They are chosen to cover the two argument kinds a printed call can get wrong: a JSON body
#: beside a query parameter, and a path parameter whose value needs encoding on the wire and
#: must NOT be encoded in the Python source.
COPY_OUT_HARNESS = textwrap.dedent("""
    import { JmftsClient, asPython } from "%(client)s/index.js";

    const seen = [];
    const client = new JmftsClient({
      baseUrl: "http://appliance:8100",
      getCredential: () => "SECRET-TOKEN",
      fetchImpl: async () =>
        new Response("{}", { status: 200, headers: { "content-type": "application/json" } }),
    });
    client.onCall((event) => seen.push(event));

    await client.hybrid_search({ request: { query: "late interaction", limit: 5 }, rerank: true });
    await client.get_presentation({ usetype: "wiki:arxiv" });

    const out = {};
    for (const event of seen) {
      out[event.op_id] = asPython(event, { baseUrl: "http://appliance:8100" });
    }
    console.log(JSON.stringify(out));
    """)


@needs_node
def test_copy_out_prints_python_the_real_client_would_accept(tmp_path):
    """Property 3 of step 23, checked end to end rather than by eye.

    The printed call is parsed as Python and its keyword arguments are BOUND against the
    signature ``_verbs.py`` actually declares. That is the difference between a worked example
    and a worked example that runs: a renamed parameter, or an argument printed positionally
    where the verb wants a keyword, fails here instead of in somebody's terminal.

    It also holds the encoding boundary. ``wiki:arxiv`` goes on the wire as ``wiki%3Aarxiv``
    and must appear in the Python source as the value, not as the escape.
    """
    import ast
    import inspect

    from jmfts_client.remote import RemoteJmftsClient

    harness = tmp_path / "copyout.mjs"
    harness.write_text(COPY_OUT_HARNESS % {"client": TARGET_DIR.as_uri()}, encoding="utf-8")
    done = subprocess.run([NODE, str(harness)], capture_output=True, text=True, cwd=tmp_path)
    assert done.returncode == 0, done.stderr or done.stdout
    printed = json.loads(done.stdout)

    assert set(printed) == {
        "SearchService.hybrid_search",
        "UsetypePresentationService.get_presentation",
    }
    assert "SECRET-TOKEN" not in done.stdout

    for op_id, source in printed.items():
        tree = ast.parse(source)  # a syntax error here is a printed example that does not run
        calls = [
            node
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and isinstance(node.func.value, ast.Name)
            and node.func.value.id == "client"
        ]
        assert len(calls) == 1, f"{op_id}: expected one client call in\n{source}"
        (call,) = calls
        verb = getattr(RemoteJmftsClient, call.func.attr)
        assert call.func.attr == op_id.split(".")[-1]
        # `self` is bound on an instance, so drop it before binding the printed keywords.
        signature = inspect.signature(verb).replace(
            parameters=list(inspect.signature(verb).parameters.values())[1:]
        )
        signature.bind(**{keyword.arg: None for keyword in call.keywords})
        assert not call.args, f"{op_id} printed a positional argument; the verbs take keywords"

    presentation = printed["UsetypePresentationService.get_presentation"]
    assert 'usetype="wiki:arxiv"' in presentation
    assert "%3A" not in presentation


DENO = shutil.which("deno")

#: Two probes: one that must type-check and one that must not. The second is what stops the
#: first being vacuous — a declaration file too loose to reject anything type-checks
#: everything. Neither names a response field, so a contract renaming one does not fail this.
TYPE_PROBE = """
import type { JmftsClient } from "./verbs.d.ts";
import type { CallEvent } from "./transport.d.ts";
import type { SearchResponse, CapabilitiesResponse } from "./verbs.d.ts";

declare const client: JmftsClient;

export async function good(): Promise<string> {
  const hits: SearchResponse = await client.hybrid_search({
    request: { query: "late interaction" },
    rerank: true,
  });
  const caps: CapabilitiesResponse = await client.capabilities({ corpus: true });
  await client.get_presentation({ usetype: "markdown" });
  return `${hits} ${caps}`;
}

export function widen(event: CallEvent): string {
  return `${event.op_id} ${event.status} ${event.ms}`;
}
"""

BAD_TYPE_PROBE = """
import type { JmftsClient } from "./verbs.d.ts";

declare const client: JmftsClient;

export async function bad(): Promise<void> {
  await client.hybrid_search({ request: { query: 17 } });
  await client.capabilities({ corpuss: true });
}
"""


@pytest.mark.skipif(DENO is None, reason="no TypeScript checker on PATH")
def test_the_generated_declarations_type_check(tmp_path):
    """The 3900 generated declaration lines are the part nothing else looks at.

    ``verbs.d.ts`` is what a TypeScript view checks against, and a declaration file with a
    syntax error or an unresolvable reference fails silently — the checker falls back to
    ``any`` and everything passes. This runs a checker over the real bundle.

    Deno rather than ``tsc`` because Deno type-checks TypeScript without a compiler install
    or a ``tsconfig.json``, and because it is what is here. The ``@ts-self-types`` pragma at
    the top of each ``.js`` is what points it at the declarations; ``tsc`` finds them from the
    filename and does not need it.
    """
    # Copied out rather than probed in place: TARGET_DIR is checked file-for-file by
    # ``test_the_client_directory_holds_nothing_else``, and a scratch file left there by a
    # crashed run would fail a different test with a confusing message.
    work = tmp_path / "client"
    shutil.copytree(TARGET_DIR, work)
    (work / "probe.ts").write_text(TYPE_PROBE, encoding="utf-8")
    (work / "negative.ts").write_text(BAD_TYPE_PROBE, encoding="utf-8")

    good = subprocess.run(
        [DENO, "check", "--no-lock", str(work / "probe.ts")], capture_output=True, text=True
    )
    assert good.returncode == 0, good.stderr or good.stdout
    bad = subprocess.run(
        [DENO, "check", "--no-lock", str(work / "negative.ts")], capture_output=True, text=True
    )
    assert bad.returncode != 0, (
        "the declarations accepted a call with a wrong argument type and an unknown "
        "parameter, so they are too loose to be checking anything"
    )
