"""``docs/reference/`` is generated, and this is what stops it going stale.

Same seal as ``tests/test_client_codegen.py`` puts on ``_verbs.py``, for the same reason: a
generated artefact checked into the tree is only worth what its staleness check is worth. A
reference page that has drifted is a wrong answer with a citation, which is worse than no
page at all.

Reads files and registries. No database, no optional dependency.
"""

from __future__ import annotations

from pathlib import Path

from scripts.generate_reference import TARGET_DIR, generate
from tests.conftest import internal_tree_only

REPO = Path(__file__).resolve().parents[1]


@internal_tree_only
def test_reference_pages_are_not_stale():
    """Every page on disk is what the generator would write from the live registries."""
    for name, expected in generate().items():
        path = TARGET_DIR / name
        assert path.exists(), f"{path} is missing; run python -m scripts.generate_reference"
        assert path.read_text(encoding="utf-8") == expected, (
            f"{path} is stale. It is generated from the registries, so the fix is to run "
            "python -m scripts.generate_reference, not to edit the page."
        )


@internal_tree_only
def test_every_reference_page_carries_the_do_not_edit_banner():
    """A reader who opens one of these has to be told not to edit it."""
    for path in sorted(TARGET_DIR.glob("*.md")):
        head = path.read_text(encoding="utf-8").splitlines()[0]
        assert "GENERATED BY scripts/generate_reference.py" in head, (
            f"{path} has no generation banner. Either it is generated and the banner is "
            "missing, or it is hand-written and does not belong in docs/reference/."
        )


@internal_tree_only
def test_reference_pages_are_all_generated():
    """Nothing hand-written lives in ``docs/reference/``.

    The directory is published as a whole (``tests/test_readme_links.py::PUBLISHED``), so
    a hand-written page dropped in here would ship without ever passing the staleness
    check above.
    """
    on_disk = {p.name for p in TARGET_DIR.glob("*.md")}
    assert on_disk == set(generate()), (
        f"docs/reference/ holds {sorted(on_disk)}; the generator writes "
        f"{sorted(generate())}. Add the page to scripts/generate_reference.py, or take it "
        "out of a directory the release publishes wholesale."
    )
