"""Transport-neutral request/response contracts.

These Pydantic models are the SINGLE definition of JMFTS's data shapes, shared by every
delivery surface: the in-process ``LocalJmftsClient``, the generated REST adapter, the
OpenAPI document, and the generated ``RemoteJmftsClient`` beside this package.

They live in the CLIENT distribution, which is the far side of a move they made twice.
First out of ``api/schemas.py`` into ``jmfts_core.contracts``, so the service layer could
depend on them without importing FastAPI. Then out of ``jmfts_core`` entirely, so a
consumer who only calls an appliance installs pydantic and httpx instead of sqlalchemy,
pgvector and transformers. ``jmfts_core.rest.schemas`` still re-exports every name here,
so ``from jmfts_core.rest.schemas import X`` keeps working for anything inside the server.

Rule of the house, unchanged in substance and now enforceable by packaging: the server may
import contracts; contracts may import neither the server nor any web framework. A model
that needs a scheduler or prober type is not a contract — its adapter belongs in
``jmfts_core/explain_wire.py``, which is where the ``EXPLAIN`` builders went for exactly
this reason. ``tests/test_api_parity.py`` and
``tests/test_client_codegen.py::test_client_package_does_not_import_the_server`` hold it.
"""

from jmfts_client.contracts.document import (
    CellNoteResponse,
    CellRowResponse,
    ChunkItem,
    ChunkRequest,
    ChunkResponse,
    DocumentCellsResponse,
    DocumentCreate,
    DocumentResponse,
    DocumentTokensResponse,
    DocumentUpdate,
    FactExtractionRequest,
    FactExtractionResponse,
    LinkCreate,
    LinkResponse,
    PortfolioRaptorRequest,
    RaptorLayerItem,
    RaptorRequest,
    RaptorResponse,
    SegmentExtractionItem,
    SegmentItem,
    SegmentRequest,
    SegmentResponse,
    StructuralSplitRequest,
    StructuralSplitResponse,
    StructuralSplitSectionItem,
    SubtreeResponse,
    TokenEmbeddingResponse,
)
from jmfts_client.contracts.conversation import (
    ConversationIngestRequest,
    ConversationIngestResponse,
    ConversationMessage,
    ConversationStageResult,
)
from jmfts_client.contracts.attempt import (
    AttemptRecord,
    param_fingerprint,
)
from jmfts_client.contracts.upload import (
    FileUploadResponse,
    IngestFrontierResponse,
    UploadedFile,
)
from jmfts_client.contracts.index import (
    IndexCreate,
    IndexResponse,
)
from jmfts_client.contracts.ingest import (
    IngestRequest,
    IngestResponse,
    IngestStageResult,
    PipelineInfo,
    PipelineStageInfo,
)
from jmfts_client.contracts.graph import (
    CentralityResponse,
    CentralityScoreItem,
    CommunityItem,
    CommunityMember,
    CommunityResponse,
    GraphDiffResponse,
    GraphStatsResponse,
    LintFinding,
    LintRequest,
    LintResponse,
    SpineBranchAlternative,
    SpineBranchPoint,
    SpineItem,
    SpineResponse,
    SubtreeAuthorityItem,
    SubtreeAuthorityResponse,
    TopDescendantItem,
)
from jmfts_client.contracts.rdf import (
    OntologyImportResponse,
    OntologyResponse,
    PredicateImportConflict,
    ShapeBindingCreate,
    ShapeBindingResponse,
    ShapeProperty,
    ShapeSummary,
    TurtleDocument,
    TurtleExportResponse,
)
from jmfts_client.contracts.search import (
    AutoSearchRequest,
    AutoSearchResponse,
    HybridSearchRequest,
    RoutingMetadata,
    SearchRequest,
    SearchResponse,
    SearchResultItem,
    SourceReference,
    SynthesizeRequest,
    SynthesizeResponse,
)
from jmfts_client.contracts.search_context import (
    SearchContextCreate,
    SearchContextResponse,
    SearchContextUpdate,
)
from jmfts_client.contracts.template import (
    TemplateCreate,
    TemplateRenderRequest,
    TemplateRenderResponse,
    TemplateResponse,
    TemplateSearchRequest,
    TemplateUpdate,
    TemplateVariable,
)
from jmfts_client.contracts.triple import (
    PathResponse,
    PathStep,
    PredicateCreate,
    PredicateResponse,
    TripleCreate,
    TripleDetailResponse,
    TripleInvalidateRequest,
    TripleResponse,
    TripleSupersedRequest,
)
from jmfts_client.contracts.usetype_presentation import (
    UsetypePresentationCreate,
    UsetypePresentationResponse,
    UsetypePresentationUpdate,
)
from jmfts_client.contracts.runner import (
    DOC_DTYPE,
    TOKEN_DTYPE,
    RunnerEmbedRequest,
    RunnerEmbedResponse,
    RunnerEmbedTokensRequest,
    RunnerEmbedTokensResponse,
    RunnerFit,
    RunnerInfo,
    RunnerTokenItem,
    decode_matrix,
    decode_vector,
    encode_vector,
)
from jmfts_client.contracts.view import (
    BackReferenceItem,
    BackReferenceResponse,
    BreadcrumbResponse,
    ViewAncestor,
    ViewChildStub,
    ViewLinkRef,
    ViewPresentation,
    ViewResponse,
    ViewTripleRef,
)

__all__ = [
    "DOC_DTYPE",
    "TOKEN_DTYPE",
    "RunnerEmbedRequest",
    "RunnerEmbedResponse",
    "RunnerEmbedTokensRequest",
    "RunnerEmbedTokensResponse",
    "RunnerFit",
    "RunnerInfo",
    "RunnerTokenItem",
    "decode_matrix",
    "decode_vector",
    "encode_vector",
    "CentralityResponse",
    "CentralityScoreItem",
    "CommunityItem",
    "CommunityMember",
    "CommunityResponse",
    "GraphDiffResponse",
    "GraphStatsResponse",
    "LintFinding",
    "LintRequest",
    "LintResponse",
    "SpineBranchAlternative",
    "SpineBranchPoint",
    "SpineItem",
    "SpineResponse",
    "SubtreeAuthorityItem",
    "SubtreeAuthorityResponse",
    "TopDescendantItem",
    "ConversationIngestRequest",
    "ConversationIngestResponse",
    "ConversationMessage",
    "ConversationStageResult",
    "AttemptRecord",
    "param_fingerprint",
    "FileUploadResponse",
    "IngestFrontierResponse",
    "UploadedFile",
    "IndexCreate",
    "IndexResponse",
    "IngestRequest",
    "IngestResponse",
    "IngestStageResult",
    "PipelineInfo",
    "PipelineStageInfo",
    "DocumentResponse",
    "CellNoteResponse",
    "CellRowResponse",
    "ChunkItem",
    "ChunkRequest",
    "ChunkResponse",
    "DocumentCellsResponse",
    "DocumentCreate",
    "DocumentTokensResponse",
    "DocumentUpdate",
    "FactExtractionRequest",
    "FactExtractionResponse",
    "LinkCreate",
    "LinkResponse",
    "PortfolioRaptorRequest",
    "RaptorLayerItem",
    "RaptorRequest",
    "RaptorResponse",
    "SegmentExtractionItem",
    "SegmentItem",
    "SegmentRequest",
    "SegmentResponse",
    "StructuralSplitRequest",
    "StructuralSplitResponse",
    "StructuralSplitSectionItem",
    "SubtreeResponse",
    "TokenEmbeddingResponse",
    "OntologyImportResponse",
    "OntologyResponse",
    "PredicateImportConflict",
    "ShapeBindingCreate",
    "ShapeBindingResponse",
    "ShapeProperty",
    "ShapeSummary",
    "TurtleDocument",
    "TurtleExportResponse",
    "AutoSearchRequest",
    "AutoSearchResponse",
    "HybridSearchRequest",
    "RoutingMetadata",
    "SearchRequest",
    "SearchResponse",
    "SearchResultItem",
    "SourceReference",
    "SynthesizeRequest",
    "SynthesizeResponse",
    "SearchContextCreate",
    "SearchContextResponse",
    "SearchContextUpdate",
    "TemplateCreate",
    "TemplateRenderRequest",
    "TemplateRenderResponse",
    "TemplateResponse",
    "TemplateSearchRequest",
    "TemplateUpdate",
    "TemplateVariable",
    "PathResponse",
    "PathStep",
    "PredicateCreate",
    "PredicateResponse",
    "TripleCreate",
    "TripleDetailResponse",
    "TripleInvalidateRequest",
    "TripleResponse",
    "TripleSupersedRequest",
    "UsetypePresentationCreate",
    "UsetypePresentationResponse",
    "UsetypePresentationUpdate",
    "BackReferenceItem",
    "BackReferenceResponse",
    "BreadcrumbResponse",
    "ViewAncestor",
    "ViewChildStub",
    "ViewLinkRef",
    "ViewPresentation",
    "ViewResponse",
    "ViewTripleRef",
]
