"""Transport-neutral request/response contracts.

These Pydantic models are the SINGLE definition of JMFTS's data shapes, shared by
every delivery surface: the in-process Python API and the generated REST adapter.
They live in ``jmfts_core`` — NOT ``api`` — so the service layer can depend on them
without importing FastAPI. ``api/schemas.py``
re-exports every name here for backward compatibility, so existing
``from api.schemas import X`` imports keep working.

Rule of the house: core may import contracts; contracts may not import ``api`` or
``fastapi``. ``tests/test_api_parity.py`` enforces this.
"""

from jmfts_core.contracts.document import (
    ChunkItem,
    ChunkRequest,
    ChunkResponse,
    DocumentCreate,
    DocumentResponse,
    DocumentTokensResponse,
    DocumentUpdate,
    FactExtractionRequest,
    FactExtractionResponse,
    LinkCreate,
    LinkResponse,
    PortfolioRaptorRequest,
    RaptorLayerItem,
    RaptorRequest,
    RaptorResponse,
    SegmentExtractionItem,
    SegmentItem,
    SegmentRequest,
    SegmentResponse,
    StructuralSplitRequest,
    StructuralSplitResponse,
    StructuralSplitSectionItem,
    SubtreeResponse,
    TokenEmbeddingResponse,
)
from jmfts_core.contracts.conversation import (
    ConversationIngestRequest,
    ConversationIngestResponse,
    ConversationMessage,
    ConversationStageResult,
)
from jmfts_core.contracts.attempt import (
    AttemptRecord,
    param_fingerprint,
)
from jmfts_core.contracts.upload import (
    FileUploadResponse,
    IngestFrontierResponse,
    UploadedFile,
)
from jmfts_core.contracts.index import (
    IndexCreate,
    IndexResponse,
)
from jmfts_core.contracts.ingest import (
    IngestRequest,
    IngestResponse,
    IngestStageResult,
    PipelineInfo,
    PipelineStageInfo,
)
from jmfts_core.contracts.graph import (
    CentralityResponse,
    CentralityScoreItem,
    CommunityItem,
    CommunityMember,
    CommunityResponse,
    GraphDiffResponse,
    GraphStatsResponse,
    LintFinding,
    LintRequest,
    LintResponse,
    SpineBranchAlternative,
    SpineBranchPoint,
    SpineItem,
    SpineResponse,
    SubtreeAuthorityItem,
    SubtreeAuthorityResponse,
    TopDescendantItem,
)
from jmfts_core.contracts.search import (
    AutoSearchRequest,
    AutoSearchResponse,
    HybridSearchRequest,
    RoutingMetadata,
    SearchRequest,
    SearchResponse,
    SearchResultItem,
    SourceReference,
    SynthesizeRequest,
    SynthesizeResponse,
)
from jmfts_core.contracts.search_context import (
    SearchContextCreate,
    SearchContextResponse,
    SearchContextUpdate,
)
from jmfts_core.contracts.template import (
    TemplateCreate,
    TemplateRenderRequest,
    TemplateRenderResponse,
    TemplateResponse,
    TemplateSearchRequest,
    TemplateUpdate,
    TemplateVariable,
)
from jmfts_core.contracts.triple import (
    PathResponse,
    PathStep,
    PredicateCreate,
    PredicateResponse,
    TripleCreate,
    TripleDetailResponse,
    TripleInvalidateRequest,
    TripleResponse,
    TripleSupersedRequest,
)
from jmfts_core.contracts.usetype_presentation import (
    UsetypePresentationCreate,
    UsetypePresentationResponse,
    UsetypePresentationUpdate,
)
from jmfts_core.contracts.view import (
    BackReferenceItem,
    BackReferenceResponse,
    BreadcrumbResponse,
    ViewAncestor,
    ViewChildStub,
    ViewLinkRef,
    ViewPresentation,
    ViewResponse,
    ViewTripleRef,
)

__all__ = [
    "CentralityResponse",
    "CentralityScoreItem",
    "CommunityItem",
    "CommunityMember",
    "CommunityResponse",
    "GraphDiffResponse",
    "GraphStatsResponse",
    "LintFinding",
    "LintRequest",
    "LintResponse",
    "SpineBranchAlternative",
    "SpineBranchPoint",
    "SpineItem",
    "SpineResponse",
    "SubtreeAuthorityItem",
    "SubtreeAuthorityResponse",
    "TopDescendantItem",
    "ConversationIngestRequest",
    "ConversationIngestResponse",
    "ConversationMessage",
    "ConversationStageResult",
    "AttemptRecord",
    "param_fingerprint",
    "FileUploadResponse",
    "IngestFrontierResponse",
    "UploadedFile",
    "IndexCreate",
    "IndexResponse",
    "IngestRequest",
    "IngestResponse",
    "IngestStageResult",
    "PipelineInfo",
    "PipelineStageInfo",
    "DocumentResponse",
    "ChunkItem",
    "ChunkRequest",
    "ChunkResponse",
    "DocumentCreate",
    "DocumentTokensResponse",
    "DocumentUpdate",
    "FactExtractionRequest",
    "FactExtractionResponse",
    "LinkCreate",
    "LinkResponse",
    "PortfolioRaptorRequest",
    "RaptorLayerItem",
    "RaptorRequest",
    "RaptorResponse",
    "SegmentExtractionItem",
    "SegmentItem",
    "SegmentRequest",
    "SegmentResponse",
    "StructuralSplitRequest",
    "StructuralSplitResponse",
    "StructuralSplitSectionItem",
    "SubtreeResponse",
    "TokenEmbeddingResponse",
    "AutoSearchRequest",
    "AutoSearchResponse",
    "HybridSearchRequest",
    "RoutingMetadata",
    "SearchRequest",
    "SearchResponse",
    "SearchResultItem",
    "SourceReference",
    "SynthesizeRequest",
    "SynthesizeResponse",
    "SearchContextCreate",
    "SearchContextResponse",
    "SearchContextUpdate",
    "TemplateCreate",
    "TemplateRenderRequest",
    "TemplateRenderResponse",
    "TemplateResponse",
    "TemplateSearchRequest",
    "TemplateUpdate",
    "TemplateVariable",
    "PathResponse",
    "PathStep",
    "PredicateCreate",
    "PredicateResponse",
    "TripleCreate",
    "TripleDetailResponse",
    "TripleInvalidateRequest",
    "TripleResponse",
    "TripleSupersedRequest",
    "UsetypePresentationCreate",
    "UsetypePresentationResponse",
    "UsetypePresentationUpdate",
    "BackReferenceItem",
    "BackReferenceResponse",
    "BreadcrumbResponse",
    "ViewAncestor",
    "ViewChildStub",
    "ViewLinkRef",
    "ViewPresentation",
    "ViewResponse",
    "ViewTripleRef",
]
