"""Generate ``docs/reference/*.md`` — three declarative pages, from the live registries.

Three questions an integrator asks before sending anything, each with one page and nothing
but tables on it:

===========================  ==========================================================
``INGEST.md``                what can be ingested
``INDEXING.md``              what gets indexed, and by which rung
``RETRIEVAL.md``             what can be retrieved, and under which filters
===========================  ==========================================================

GENERATED, and generated for the reason the client is. Every fact on these pages already
exists as a declaration the appliance reads at runtime — ``INGEST_USETYPES``,
``TASK_ROWS``, ``ATOMS``, ``probe``'s format tables, ``SEARCH_METHODS``, ``Settings``. A
hand-written table beside a declaration is a second copy free to drift, and a reference
page that has drifted is worse than none: it is a wrong answer with a citation. So the
declarations are the source and this renders them.

These pages carry no history, no sprint numbers and no argument. They are the redacted
half of ``docs/``: the working record explains WHY the appliance is shaped this way and
stays internal, and these say WHAT it accepts, and ship. ``GET /capabilities`` answers a
narrower version of the same three questions for a RUNNING appliance, from the same
registries.

Run it from the repository root::

    python -m scripts.generate_reference            # rewrite the pages
    python -m scripts.generate_reference --check    # exit 1 if any page is stale

``tests/test_reference_docs.py`` runs the check, so a new ingest rung or retrieval method
cannot land without its row.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from jmfts_client.contracts.search import DEFAULT_HYBRID_METHODS, SEARCH_METHODS
from jmfts_core.atoms import ATOMS
from jmfts_core.config import Settings
from jmfts_core.ingest_options import INGEST_USETYPES
from jmfts_core.ingest_tasks import (
    SCOPE_ROOT,
    TASK_HANDLERS,
    TASK_ROWS,
)
from jmfts_core.probe import PROBERS_AVAILABLE, detectable_formats
from jmfts_core.repositories.search import TUNED_HYBRID_WEIGHTS
from jmfts_core.services.meta_service import _EXTRAS

REPO = Path(__file__).resolve().parents[1]
TARGET_DIR = REPO / "docs" / "reference"

BANNER = (
    "<!-- GENERATED BY scripts/generate_reference.py — DO NOT EDIT.\n"
    "     Every table below is rendered from a registry the appliance reads at runtime.\n"
    "     Change the declaration, then run `python -m scripts.generate_reference`. -->\n"
)


def _table(headers: list[str], rows: list[list[str]]) -> str:
    """A GitHub-flavoured markdown table. Empty cells become an em dash, never blank."""
    out = ["| " + " | ".join(headers) + " |"]
    out.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        out.append("| " + " | ".join(cell if cell else "—" for cell in row) + " |")
    return "\n".join(out)


def _code_list(values) -> str:
    """``a``, ``b``, ``c`` — backticked, comma-separated, em dash when empty."""
    values = list(values)
    return ", ".join(f"`{v}`" for v in values) if values else "—"


# ---------------------------------------------------------------------------
# INGEST.md
# ---------------------------------------------------------------------------


def render_ingest() -> str:
    """What can be ingested: entry points, formats, and the extras each one needs."""
    usetypes = _table(
        ["usetype", "content comes from", "what it does"],
        [[f"`{name}`", f"`{u.source}`", u.description] for name, u in INGEST_USETYPES.items()],
    )

    detectable = set(detectable_formats())
    probeable = set(PROBERS_AVAILABLE)
    formats = _table(
        ["format", "identified from the bytes", "can be looked inside"],
        [[f"`{fmt}`", "yes", "yes" if fmt in probeable else "no"] for fmt in sorted(detectable)]
        + [[f"`{fmt}`", "no", "yes"] for fmt in sorted(probeable - detectable)],
    )

    extras = _table(
        ["extra", "install", "what it unlocks"],
        [[f"`{name}`", f"`{install}`", provides] for name, _, provides, install in _EXTRAS],
    )

    return f"""{BANNER}
# What can be ingested

Three tables. The first is what `POST /ingest` accepts as an entry point, the second is
what the bytes may be, the third is what an optional dependency buys. `GET /capabilities`
answers all three for a running appliance.

## Entry points

A `usetype` names where the content comes from, not what format it is. `probe` measures
the format from the bytes; a usetype only says whether this request carries the content,
a URL, an arXiv id or a local path.

{usetypes}

## Formats

*Identified from the bytes* means `detect_format` names the format from a signature or an
archive manifest. Anything else is still accepted: the format falls back to the filename
extension, and the file node records that the evidence was a hint rather than a
measurement.

*Can be looked inside* means a prober can measure this format's structural patterns. A
format without one gets an empty pattern set, and every rung guarded on a pattern stands
down — which is the correct outcome, and it is recorded as such rather than assumed.

{formats}

## Optional dependencies

A base install carries none of these. Probing an office file needs none of them either;
opening one needs `office`.

{extras}
"""


# ---------------------------------------------------------------------------
# INDEXING.md
# ---------------------------------------------------------------------------


def _term(t) -> str:
    """One guard term, with the SENTINEL NAME kept rather than resolved.

    ``render_term`` resolves a sentinel through ``DECLARED_STRUCTURE_PATTERN`` for one
    format, and these pages are about every format at once — resolving against no format
    renders the sentinel as ``None``, which is not a term. So the name stays as written,
    and the page says what a name beginning ``@`` means.
    """
    if t.op is None:
        return str(t.left)
    right = t.right if hasattr(t.right, "group") else repr(t.right)
    return f"{t.left} {t.op} {right}"


def _scope(row) -> str:
    """A row's scope as a phrase: the file node, or the nodes a rule produced."""
    scope = row.scope
    if scope.kind == SCOPE_ROOT:
        return "the file node"
    parts = []
    if scope.produced_by:
        parts.append("produced by " + _code_list(scope.produced_by))
    if scope.usetypes:
        parts.append("usetype " + _code_list(scope.usetypes))
    return f"`{scope.kind}` nodes" + (" " + ", ".join(parts) if parts else "")


def render_indexing() -> str:
    """What gets indexed, by which rung: the task table and what each atom reads/writes."""
    rows = _table(
        ["task", "runs on", "writes", "requires", "does not run when", "after"],
        [
            [
                f"`{row.task}`",
                _scope(row),
                f"`{row.write_mode}`" if row.write_mode else "nothing (always skipped)",
                ", ".join(f"`{_term(t)}`" for t in row.requires),
                ", ".join(f"`{_term(t)}`" for t in row.forbids),
                _code_list(row.after + row.after_any),
            ]
            for row in TASK_ROWS
        ],
    )

    atoms = _table(
        ["task", "reads", "writes", "cost"],
        [
            [
                f"`{name}`",
                _code_list(f"{f.name}@{f.locus}" for f in atom.consumes),
                _code_list(f"{f.name}@{f.locus}" for f in atom.produces),
                f"`{atom.cost_class}`",
            ]
            for name, atom in sorted(ATOMS.items())
        ],
    )

    unrowed = sorted(set(TASK_HANDLERS) - {row.task for row in TASK_ROWS})

    return f"""{BANNER}
# What gets indexed, and by which rung

There is one ingest path and it is the task queue. A document's tasks are not a fixed
sequence: each rung below declares the conditions under which it applies, and the planner
reads those declarations. Adding a rung means registering a handler, not editing a ladder
of conditionals.

## The rungs

*Requires* must all hold; *does not run when* is a disjunction of exclusions. A name
beginning `@` is a per-format sentinel — it resolves to whichever pattern that format uses
to make the claim, and a format with no entry makes the requirement unsatisfiable rather
than false. A pattern nothing measures leaves the rung standing down with that as its
stated reason.

*Runs on* is the rung's scope. A rung scoped to nodes another rung produced is not
evaluated when the file is first probed — those nodes do not exist yet — and is asked for
at the moment they do.

{rows}

## What each task reads and writes

A locus separates the node a task reads from the node it writes: `self` is the node the
task runs on, `children` and `subtree` are the regions below it, and `ancestor` is a read
of the node above (legal only as a read).

{atoms}

## Handlers with no row

Registered task types that the table above does not plan, because something other than the
per-document planner asks for them: the upload path enqueues `probe` and whichever
`fetch:*` the entry point names, the settling walk asks for the rollups, and the rest are
operations a caller invokes directly.

{_code_list(unrowed)}

## Retrieval visibility

A document carries a `settled` state and the retrieval indexes are partial on it, so a
node whose tasks are still running is invisible to search until the settling walk
completes it. That is why a freshly uploaded file returns nothing and then returns
everything, rather than returning half a tree.
"""


# ---------------------------------------------------------------------------
# RETRIEVAL.md
# ---------------------------------------------------------------------------

#: Every retrieval method, what it reads, and what a document must carry to be reachable
#: by it. The three columns are facts about the appliance, not about any corpus;
#: ``GET /capabilities?corpus=true`` answers the corpus half.
_METHOD_NOTES: dict[str, tuple[str, str]] = {
    "vector": (
        "`documents.embed`, an HNSW index over the 768-dim document vector",
        "a document embedding (`auto_embed`, or the `embed` task)",
    ),
    "fulltext": (
        "a PostgreSQL expression GIN index over `title || content`",
        "nothing — the index is an expression over columns every document has",
    ),
    "bm25": (
        "the inverted index tables (`search_term_postings`, `search_term_stats`)",
        "a row in a named BM25 index (`auto_index_bm25`, or the `index:bm25` task)",
    ),
    "maxsim": (
        "`token_embeddings`, per-token 256-dim vectors, scored by late interaction",
        "token embeddings (`embed_tokens`, or `POST /documents/{id}/tokens`)",
    ),
}


def _default(field: str) -> list[str]:
    """A ``Settings`` field's DECLARED default, not this machine's resolved value.

    ``Settings()`` reads the environment and ``.env``, so instantiating it would render a
    page that says what one operator configured and make the staleness check fail on
    anybody else's machine. The declared default is the fact about the software.
    """
    return list(Settings.model_fields[field].default)


def render_retrieval() -> str:
    """What can be retrieved and under which filters."""

    methods = _table(
        ["method", "reads", "a document is reachable only with"],
        [[f"`{m}`", _METHOD_NOTES[m][0], _METHOD_NOTES[m][1]] for m in SEARCH_METHODS],
    )

    weights = _table(
        ["method", "weight in the default fusion"],
        [
            [f"`{m}`", f"`{TUNED_HYBRID_WEIGHTS[m]}`" if m in TUNED_HYBRID_WEIGHTS else "`1.0`"]
            for m in SEARCH_METHODS
        ],
    )

    filters = _table(
        ["filter", "default", "what it does"],
        [
            [
                "`usetype`",
                "unset",
                "keep only this usetype. Supports `*` and `?`. Overrides `exclude_types` "
                "entirely.",
            ],
            [
                "`exclude_types`",
                _code_list(_default("search_exclude_usetypes")),
                "drop these usetypes. **Applied when the request names none** — this is the "
                "filter that shortens a result list with no explanation. Pass `[]` to "
                "disable it.",
            ],
            ["`parent_id`", "unset", "keep only documents in this subtree."],
            [
                "`as_of`",
                "unset",
                "keep only documents whose domain clock `COALESCE(event_time, created_at)` "
                "is at or before this instant.",
            ],
            ["`threshold`", "`0.0`", "vector search only: minimum cosine similarity."],
            ["`limit`", "`10`", "result ceiling, 1 to 100."],
            [
                "settled state",
                "always applied",
                "documents still being ingested are excluded, and this cannot be turned " "off.",
            ],
            [
                "subtree access",
                "always applied",
                "a document under an access-control root is returned only to a principal "
                "granted read on it. A document under no such root is unprotected.",
            ],
        ],
    )

    return f"""{BANNER}
# What can be retrieved, and under which filters

Every search response carries an `applied` block reporting the resolved methods, the
resolved weights and the usetype exclusions that were applied. Read it rather than
inferring from the result count.

## Methods

{methods}

`POST /search/hybrid` fuses several of these with Reciprocal Rank Fusion. Omitting
`methods` runs {_code_list(DEFAULT_HYBRID_METHODS)}. An unrecognised method name is
rejected, not ignored.

## Fusion weights

The default weights are tuned for the default method pair. A fused method with no tuned
weight is multiplied by `1.0`, which is larger than either tuned value — so adding a
method without adding its weight changes the ranking more than the addition itself does.
Pass an explicit `weights` map to control this, or `{{}}` for equal-weight RRF.

{weights}

## Filters

{filters}

## Exclusion has two layers

`exclude_types` is a search-time filter and is reported in `applied.exclude_types`. BM25
also excludes at INDEX time — {_code_list(_default("bm25_exclude_usetypes"))} are never
written to an inverted index at all — so no search argument brings them back to the bm25
leg. Re-indexing does.
"""


PAGES = {
    "INGEST.md": render_ingest,
    "INDEXING.md": render_indexing,
    "RETRIEVAL.md": render_retrieval,
}


def generate() -> dict[str, str]:
    """Every page's rendered text, keyed by filename."""
    return {name: render() for name, render in PAGES.items()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="generate_reference", description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any page on disk differs from what this would write",
    )
    args = parser.parse_args(argv)

    rendered = generate()
    if args.check:
        stale = [
            name
            for name, text in rendered.items()
            if not (TARGET_DIR / name).exists()
            or (TARGET_DIR / name).read_text(encoding="utf-8") != text
        ]
        if stale:
            print(
                f"stale: {', '.join(stale)}\nRun: python -m scripts.generate_reference",
                file=sys.stderr,
            )
            return 1
        return 0

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in rendered.items():
        (TARGET_DIR / name).write_text(text, encoding="utf-8")
        print(f"wrote {TARGET_DIR / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
